#FROM alpine:3.3
FROM aarch64/alpine:edge

WORKDIR /home/flux

RUN apk add --no-cache 'git>=2.3.0' openssh python py-yaml ca-certificates

COPY ./kubeservice /usr/local/bin/
ADD ./migrations.tar /home/flux/
COPY ./fluxsvc /usr/local/bin/

ENTRYPOINT [ "fluxsvc" ]
